version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose backend on host
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose frontend on host
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
